[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer_runs = 44444444
via_ir = true
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}, { access = "read", path = "./out"}, {access = "read", path = "./test/bin"}, {access = "read", path = "./test"}, {access = "read", path = "../../src/data/"}]
solc = "0.8.26"
evm_version = "cancun"
gas_limit = "300000000"

[profile.default.fuzz]
runs = 1
seed = "0x4444"

[profile.pr.fuzz]
runs = 1

[profile.ci.fuzz]
runs = 1

[profile.debug]
via_ir = false
optimizer_runs = 200
fuzz.runs = 1

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
